<div class="max-w-4xl mx-auto mt-4">
    <div class="bg-gray-50 border border-gray-200 rounded-lg p-12">
        <h1 class="text-6xl font-normal mb-4">Анализатор страниц</h1>

        <p class="text-xl mb-4">
            Бесплатно проверяйте сайты на SEO-пригодность
        </p>

        <form class="flex gap-4">
            <input
                type="text"
                name="url"
                placeholder="https://www.example.com"
                class="flex-1 rounded-lg"
            >

            <button
                type="submit"
                class="bg-blue-600 text-white px-12 py-3 rounded-lg uppercase"
            >
                Проверить
            </button>
        </form>
    </div>
</div>